fix: error mismatch
RGB-WG/rgb pull request #254
Opened 2024-09-23 01:06 UTC by Crayon-Shin-chan-1024

because of recently modify for storage backend, it breaks the error chain

2024-09-23 14:15 UTC, Crayon-Shin-chan-1024 commented
> Can you please run `cargo +nightly fmt --all`

i have run the command, i don't know why the rustfmt seems strange

2024-09-25 10:27 UTC, dr-orlovsky requested changes

2024-09-25 10:27 UTC, dr-orlovsky commented on cli/src/args.rs
> +            .map_err(WalletError::WalletPersist)
I think we can remove this `map_err` here and move it down, saving some clarity in the checks within `or_else`
```suggestion
```

2024-09-25 10:27 UTC, dr-orlovsky commented on cli/src/args.rs
> +            })?;
```suggestion
            })
            .map_err(WalletError::WalletPersist)?;
```

2024-09-25 10:27 UTC, dr-orlovsky commented on cli/src/args.rs
> +                        if io_err.kind() == ErrorKind::NotFound {
I do not think we need that deep construction; we can do the same way we did before with errors in errors

```suggestion
                let Some(DeserializeError::Decode(DecodeError::Io(io_err))) = err.0.downcast_ref::<DeserializeError>() else {
                    eprintln!("stock file is damaged, failing");
                    return Err(err)
                };
                if io_err.kind() == ErrorKind::NotFound {
```

2024-09-25 10:27 UTC, dr-orlovsky commented on cli/src/args.rs
> +                Err(err)
We would not need this part
```suggestion
                eprintln!("stock file is damaged, failing");
                Err(err)
```

2024-10-28 05:54 UTC, closed without merging